# 1. Використовуємо slim-версію (економія ~1 ГБ на старті)
FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Встановлюємо необхідні системні утиліти
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY lesson-3/requirements.txt .

# Встановлюємо залежності (torch/tv/pillow/numpy) згідно з requirements.txt
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Копіюємо готову TorchScript-модель та скрипти
COPY lesson-3/model.pt lesson-3/inference.py lesson-3/export_model.py ./

ENTRYPOINT ["python", "inference.py"]
CMD ["--help"]